reload-message: "&aReloaded Configuration!"
permanent-duration-translation: "Permanent"
litebans-do-not-send-silent-punishments: true
inline-webhooks: false

ban:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "New Ban!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

mute:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Mute!!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

warn:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Warn!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

kick:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Kick!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

unban:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "Player Unbanned!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Unbanned by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"

unmute:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "Player Unmuted!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Unmuted by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"

unwarn:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "Player Unwarned!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Unwarned by": "{executor}"
    "ID": "{id}"
    "Username": "{player}"
    "Reason": "{reason}"