reload-message: "&aReloaded Configuration!"
litebans-do-not-send-silent-punishments: true
inline-webhooks: false

ban:
  enabled: true
  webhook-url: "enter-url-here"
  webhook-title: "New Ban!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

mute:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Mute!!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

warn:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Warn!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"

kick:
  enabled: false
  webhook-url: "enter-url-here"
  webhook-title: "New Kick!"
  webhook-thumbnail: ""
  webhook-color: "ff0000"
  fields:
    "Banned by": "{executor}"
    "Username": "{player}"
    "Reason": "{reason}"
    "Duration": "{duration}"